config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: [:create]
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    has_attached_file :avatar, :styles => { medium: "300x300>", thumb: "100x100>" }, :default_url => ":style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :plan
  has_one :profile
  
  def has_profile
    return self.profile != nil
  end
  
  attr_accessor :stripe_card_token
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:signup) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
  # POST to /users/:user_id/profile
  def create
    # check user exists
    @user = User.find(params[:user_id])
    # create profile linked to this user
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile created!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  
  # GET to /users/:user_id/profile/edit
  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end
  
  # PATCH to /users/:user_id/profile
  def update
    @user = User.find( params[:user_id] )
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      redirect_to user_path( id: params[:user_id] )
    else
      render action: :edit
    end
  end
  
  def show
    redirect_to user_path( params[:user_id] )
    
  end
  
  private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
  end
  
  def only_current_user
    @user = User.find( params[:user_id] )
    redirect_to(root_url) unless @user == current_user
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == '2'
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end
  
  def index
    @users = User.includes(:profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def job_title_icon
        if @user.profile.job_title == "Developer"
            "<i class='fa fa-laptop job-icon'></i>".html_safe
        elsif @user.profile.job_title == "Entrepreneur"
            "<i class='fa fa-lightbulb-o job-icon'></i>".html_safe
        elsif @user.profile.job_title == "Investor"
            "<i class='fa fa-suitcase job-icon'></i>".html_safe
        end
    end
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Us</h3>
    <div class="col-md-4 col-md-offset-4">
    <%= flash[:error] %>
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevLink</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css2?family=Open+Sans:wght@400;700;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v3/", type: 'text/javascript' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            DevLink
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
            <% if user_signed_in? %>
              <% if current_user.has_profile %>
                <li><%= link_to "Community", users_path, class: "btn" %></li>
                <li><%= link_to "My Profile", user_profile_path(user_id: current_user.id), class: "btn" %></li>
                <li><%= link_to '<i class="fa fa-cog"></i>'.html_safe, edit_user_registration_path, class: "btn" %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_user_profile_path(user_id: current_user.id), class: "btn" %></li>
              <% end %>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/_dashboard.html.erb
<div class="col-md-6">
    <div class="well">
        <h2 class="text-center">New to DevLink?</h2>
        <p class="text-center">View the the new user guide to get quickly learn how to use DevLink.</p>
        <%= link_to "DevLink Guide", "#", class: 'btn btn-default btn-lg btn-block' %>
    </div>
</div>
<div class="col-md-6">
    <div class="well">
        <h2 class="text-center">The Community</h1>
        <p class="text-center">Visit the community to meet other developers, entrepreneurs, and investors!</p>
        <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
    </div>
</div>

app/views/pages/about.html.erb
<div class="container text-center container-fluid">
    <h1>About page</h1>
    <p>We are DevLink. We match businesses and entrepreneurs with developers.</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1>Welcome to DevLink</h1>
    <h3>The site that connects businesses and entrepreneurs with developers.</h3>
</div>
<div class="container home-signup-links">
  <div class="row">
    <% if user_signed_in? %>
      <div>
        <%= render 'dashboard' %>
      </div>
    <% else %>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Basic Membership</h2>
          <h4>Sign up for free and get basic access to the community.</h4>
          <br>
          <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Pro Membership</h2>
          <h4>Sign up for the pro account and get access to the community and contact information!</h4>
          <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', placeholder: "John" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control', placeholder: "Smith" %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control', placeholder: "+# (###)-###-####" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control', placeholder: "johnsmith@example.com" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: "Something about me..." %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Your Profile</h1>
    <p class="text-center">Be a part of the DevLink community and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the DevLink community and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 class="text-center">DevLink Community</h1>
            <p class="text-center">Welcome to the DevLink Community. Users must fill out their profile in order to be visible within the community.</p>
            <ul class="list-unstyled">
                <% @users.each do |user| %>
                    <% if user.profile %>
                        <li>
                            <div class="well row <%= cycle('white-bg', '') %>">
                                <div class="col-sm-4 text-center">
                                    <% if user.profile.avatar %>
                                        <%= link_to user do %>
                                            <%= image_tag user.profile.avatar.url, class: 'user-index-avatar' %>
                                        <% end %>
                                    <% end %>
                                </div>
                                <div>
                                    <%= link_to user do %>
                                        <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                                    <% end %>
                                    <p>
                                        <%= user.profile.job_title %>
                                        <% if user.plan_id == 2 %>
                                            <span class="label label-danger">PRO</span>
                                        <% end %>
                                    </p>
                                </div>
                            </div>
                        </li>
                    <% end %>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div>
  <div class="row">
    <div class="col-md-3 col-md-offset-1 text-center">
      <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
    </div>
    <div class="col-md-6">
      <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
      <div class="row">
        <div class="col-md-4">
          <h3><span><%= job_title_icon %></span><%= @user.profile.job_title %></h3>
        </div>
        <div class="col-md-4">
          <h3>
            <% if @user.plan_id == 2 %>
            <span class="label label-danger">PRO</span>
            <% end %>
          </h3>
        </div>
      </div>
      <div class="well profile-block pro-desc">
        <h3>About Me</h3>
        <%= @user.profile.description %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-md-offset-1 text-center">
      <% if user_signed_in? && (current_user.id == @user.id) %>
        <%= link_to "Edit profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <% end %>
    </div>
    <div class="col-md-6">
      <% if current_user.plan_id == 2 %>
        <div class="well profile-block pro-contact">
            <h3>Contact Information</h3>
            <p>Phone: <%= @user.profile.phone_number %></p>
            <p>Email: <%= @user.profile.contact_email %></p>
          </div>
      <% else %>
        <div class="well profile-block pro-contact">
            <h3>Contact Information</h3>
            <br>
            <p class="text-center">Sign up for DevLink Pro to view users' contact information</p>
            <br>
          </div>
      <% end %>
    </div>
  </div>
</div>